name: John.Sockwell.NYC
favicon: null
layout_spectrum: 0.2759857
typography_spectrum: 0.26354
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: John Sockwell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1b20'
    - '#e9e3e3'
    - '#86949f'
    - '#bbbcc1'
    - '#5e7086'
  brandStrength: 0.5770609
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
