name: John.Sockwell.NYC
favicon: null
layout_spectrum: 0.40616
typography_spectrum: 0.26354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1b20'
    - '#e9e3e3'
    - '#86949f'
    - '#bbbcc1'
    - '#5e7086'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
