layout_spectrum: 0.6655060364864767
typography_spectrum: 0.23871278180740774
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.7010706106666476
  lightness: 0.32586311432532966
  saturation: 0.2943530869670212
  rhythmicContrast: 0.0766535468865186
name: John Sockwell
favicon: null
author:
  name: John Sockwell
  url: john.sockwell.nyc
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/70318146-3e89-4a33-b18f-fbe5dea1a4e5.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: John Sockwell
description: 'Observer, Inventor, Explorer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
