name: john.sockwell.nyc
favicon: null
layout_spectrum: 0.61706
typography_spectrum: 0.26254
author:
  name: John Sockwell
  url: john.sockwell.nyc
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/70318146-3e89-4a33-b18f-fbe5dea1a4e5.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: John Sockwell
description: 'Observer, Inventor, Explorer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 1
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
